# -*- coding: utf-8 -*-
"""T4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2nSncfwUbSCsGxPE2be0FqNvZHEYRcs
"""

import pde
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import HTML
from matplotlib.animation import FuncAnimation
from tqdm import tqdm

grid = pde.CartesianGrid([[0,5],[0,5]],[200,200])
r_grid = grid.axes_coords[0]
dx = np.diff(r_grid).mean()

np.random.seed(42)

U0 = 1.0 + 0.1*np.random.randn(*grid.shape)
V0 = 1.0 + 0.1*np.random.randn(*grid.shape)

U = pde.ScalarField(grid, data=U0)
V = pde.ScalarField(grid, data=V0)

estado = pde.FieldCollection([U,V])

α = 0.0002
β = 0.06

eq = pde.PDE({
    "u": "α*(d2_dx2(u) + 3*d2_dy2(u)) + u - u**3 - v",
    "v": "β*(d2_dx2(v) + d2_dy2(v)) + 8*(u - v)"
},
consts={"α":α,"β":β},
bc="neumann"
)


D = max(α, β)
dt = 0.4*dx**2/(4*D)
tmax = 30

storage = pde.MemoryStorage()

eq.solve(
    estado,
    t_range=(0, tmax),
    dt=dt,
    tracker=[storage.tracker(0.2)],
    solver="scipy"
)

u_fields = storage.extract_field(0)

fig, ax = plt.subplots(figsize=(6,6))
u_fields[-1].plot(ax=ax, cmap="gray")

ax.set_title(
    f"Zebra stripes\nα={α}, β={β}\nF=u-u³-v\nG=8(u-v)"
)

plt.tight_layout()
plt.savefig("2_zebra_stripes.png", dpi=300)
plt.close()

grid = pde.CartesianGrid([[0,3],[0,3]],[200,200])
r_grid = grid.axes_coords[0]
dx = np.diff(r_grid).mean()

np.random.seed(42)

U0 = 1.0 + 0.1*np.random.randn(*grid.shape)
V0 = 1.0 + 0.1*np.random.randn(*grid.shape)

U = pde.ScalarField(grid, data=U0)
V = pde.ScalarField(grid, data=V0)

estado = pde.FieldCollection([U,V])

α = 0.0002
β = 0.06

eq = pde.PDE({
    "u": "α*laplace(u) + u - u**3 - v + x/25",
    "v": "β*laplace(v) + 8*(u - v)"
},
consts={"α":α,"β":β},
bc="neumann"
)

D = max(α,β)
dt = 0.4*dx**2/(4*D)
tmax = 40

storage = pde.MemoryStorage()

eq.solve(
    estado,
    t_range=(0,tmax),
    dt=dt,
    tracker=[storage.tracker(0.5)],
    solver='scipy'
)

u_fields = storage.extract_field(0)

fig, ax = plt.subplots(figsize=(6,6))
u_fields[-1].plot(ax=ax, cmap="inferno")

ax.set_title(
    f"Leopard spots\nα={α}, β={β}\nF=u-u³-v+x/25\nG=8(u-v)"
)

plt.tight_layout()
plt.savefig("2_patron_leopardo.png", dpi=300)
plt.close()

grid = pde.CartesianGrid([[0,6],[0,6]],[220,220])
x = grid.cell_coords[...,0]
y = grid.cell_coords[...,1]

np.random.seed(42)

k = 6

pattern = (
    np.cos(k*x) +
    np.cos(k*(-0.5*x + np.sqrt(3)/2*y)) +
    np.cos(k*(-0.5*x - np.sqrt(3)/2*y))
)

U0 = 1.0 + 0.25*pattern + 0.02*np.random.randn(*grid.shape)
V0 = 1.0 + 0.02*np.random.randn(*grid.shape)

U = pde.ScalarField(grid, data=U0)
V = pde.ScalarField(grid, data=V0)

estado = pde.FieldCollection([U,V])

α = 0.0001
β = 0.06

eq = pde.PDE({
    "u": "α*(d2_dx2(u) + d2_dy2(u)) + u - u**3 - v",
    "v": "β*(d2_dx2(v) + d2_dy2(v)) + 8*(u - v)"
},
consts={"α":α,"β":β},
bc="neumann"
)

dx = np.diff(grid.axes_coords[0]).mean()
D = max(α, β)
dt = 0.4*dx**2/(4*D)

tmax = 60

storage = pde.MemoryStorage()

eq.solve(
    estado,
    t_range=(0,tmax),
    dt=dt,
    tracker=[storage.tracker(0.5)],
    solver="scipy"
)

u_fields = storage.extract_field(0)

fig, ax = plt.subplots(figsize=(6,6))
u_fields[-1].plot(ax=ax, cmap="jet")

ax.set_title(
    f"Hexagonal crystal lattice\nα={α}, β={β}\nF=u-u³-v\nG=8(u-v)"
)

plt.tight_layout()
plt.savefig("2_red_cristalina.png", dpi=300)
plt.close()

alpha = 0.1
xmin, xmax = -20, 20
Nx = 512
dt = 0.001

T = 2*np.pi*5
tmax = 2*T

x = np.linspace(xmin, xmax, Nx)
dx = x[1] - x[0]


psi0 = np.exp(-2*(x-10)**2) * np.exp(-2j*x)
psi0 = psi0 / np.sqrt(np.sum(np.abs(psi0)**2)*dx)


def laplacian(psi):
    return (np.roll(psi,-1) - 2*psi + np.roll(psi,1)) / dx**2

def rhs(psi, V):
    return 1j * (alpha * laplacian(psi) - V * psi)

def step(psi, V):
    k1 = rhs(psi, V)
    k2 = rhs(psi + dt*k1/2, V)
    k3 = rhs(psi + dt*k2/2, V)
    k4 = rhs(psi + dt*k3, V)
    return psi + dt*(k1 + 2*k2 + 2*k3 + k4)/6

def normalize(psi):
    norm = np.sqrt(np.sum(np.abs(psi)**2)*dx)
    return psi/norm

def run_case(V, filename, title):

    psi = psi0.copy()

    fig, ax = plt.subplots(figsize=(8,4))

    line, = ax.plot(x, np.abs(psi)**2)

    Vscaled = (V - V.min())/(V.max() - V.min())
    pot_line, = ax.plot(x, 0.5*Vscaled, '--')

    ax.set_xlim(xmin, xmax)
    ax.set_ylim(0, 0.6)

    ax.set_xlabel("x")
    ax.set_ylabel(r"$|\psi|^2$")
    ax.set_title(title)

    steps_per_frame = 200
    nframes = int(tmax/dt/steps_per_frame)

    def update(frame):
        nonlocal psi

        for _ in range(steps_per_frame):
            psi = step(psi, V)

        psi = normalize(psi)

        line.set_ydata(np.abs(psi)**2)

        return line,

    ani = FuncAnimation(fig, update,
                        frames=nframes,
                        interval=30)

    ani.save(filename, fps=30)

    plt.close(fig)






V_a = x**2 / 50
run_case(V_a, "4a.mp4", "Evolución - Potencial armónico")


V_b = (x/5)**4
run_case(V_b, "4b.mp4", "Evolución - Potencial cuártico")


V_c = (x**4/100 - x**2/5)*(1/50)
run_case(V_c, "4c.mp4", "Evolución - Potencial sombrero")