# -*- coding: utf-8 -*-
"""T5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VHJot8hYVFwFtAAc1IzykUJOwNTgR-fb
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install corner

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from scipy import optimize, stats
import corner
from tqdm import tqdm
from scipy.integrate import solve_ivp
from numba import njit
from matplotlib import gridspec
random = np.random.default_rng()

data = pd.read_csv("CMB_dipole_spectrum.dat", sep=r"\s+")

freqs = data["Frequency"][1:]
F = data["Measurement"][1:]
sigma = data["Uncertainty"][1:]
freqs = np.float64(freqs)
F = np.float64(F)
sigma = np.float64(sigma)


hckb = 1.438776878
twohc = 39728.91714



def B(nu,T,mu):
    return (twohc*nu**3)/(np.exp(hckb*nu/T + mu)-1)

def dBdT(nu,T):
    eps = 1e-5
    return (B(nu,T+eps,0)-B(nu,T-eps,0))/(2*eps)

def model(nu,Tamp,Tcmb,Tgal,G):
    return Tamp*dBdT(nu,Tcmb) + G*B(nu,Tgal,-1)




def log_likelihood(theta,nu,F,sigma):
    Tamp,Tcmb,Tgal,G = theta
    Fm = model(nu,Tamp,Tcmb,Tgal,G)
    return -0.5*np.sum(((Fm-F)/sigma)**2)

def log_prior(theta):
    Tamp,Tcmb,Tgal,G = theta
    if Tamp>0 and Tcmb>0 and Tgal>0 and G>0:
        return 0.0
    else:
        return -np.nan

def log_posterior(theta,nu,F,sigma):
    lp = log_prior(theta)
    if not np.isfinite(lp):
        return -np.inf
    else:
        return lp + log_likelihood(theta,nu,F,sigma)

initial_guesses = [3.41e-3, 2.72, 13.5, 0.425e-8]

popt, pcov = curve_fit(model, freqs, F, sigma=sigma, p0=initial_guesses)

T_amp_fit, T_CMB_fit, T_Gal_fit, G_fit = popt
T_amp_uncertainty, T_CMB_uncertainty, T_Gal_uncertainty, G_uncertainty = np.sqrt(np.diag(pcov))

F_fit = model(freqs, T_amp_fit, T_CMB_fit, T_Gal_fit, G_fit)

normalized_residuals = (F - F_fit) / sigma

fig, axs = plt.subplots(2, 1, figsize=(10, 6), sharex = True)
plt.sca(axs[0])

plt.errorbar(freqs, F, yerr=sigma, fmt='o', markersize=4, label='Data')
plt.plot(freqs, F_fit, label='Fitted Model', color='red')
plt.ylabel('Flux (kJy)')
plt.title('COBE FIRAS Data with Fitted Model')
plt.legend()


plt.sca(axs[1])
plt.scatter(freqs, normalized_residuals, label='Residuals', color='red', s = 6)
plt.xlabel('Frequency (cm$^{-1}$)')
plt.ylabel('Normalized residuals')
plt.legend()
plt.close()

plt.tight_layout()

nsteps = 500000
chain = np.zeros((nsteps,4))

theta = np.array([3e-3,2.7,13,4e-9])

step = 0.001 * theta

chain[0] = theta

for i in range(1,nsteps):

    proposal = theta + np.random.normal(0,step)

    logp_new = log_posterior(proposal,freqs,F,sigma)
    logp_old = log_posterior(theta,freqs,F,sigma)

    if np.log(np.random.rand()) < logp_new-logp_old:
        theta = proposal

    chain[i] = theta

fig = corner.corner(
    chain[5000::10],
    labels=[r"$T_{amp}$",r"$T_{CMB}$",r"$T_{Gal}$",r"$G$"],
    quantiles=[0.16,0.5,0.84],
    show_titles=True,
    title_fmt=".2g"
)
plt.tight_layout()

plt.savefig("1.pdf")
plt.close()

fig = corner.corner(
    chain[5000::10],
    labels=[r"$T_{amp}$",r"$T_{CMB}$",r"$T_{Gal}$",r"$G$"],
    quantiles=[0.16,0.5,0.84],
    show_titles=True,
    title_fmt=".2g"
)
plt.tight_layout()
plt.close()
plt.savefig("1.pdf")



accepted = 0

for i in range(1,nsteps):

    proposal = theta + np.random.normal(0,step)

    logp_new = log_posterior(proposal,freqs,F,sigma)
    logp_old = log_posterior(theta,freqs,F,sigma)

    if np.log(np.random.rand()) < logp_new-logp_old:
        theta = proposal
        accepted += 1

    chain[i] = theta

N = 50
J = 1
beta = 0.5

n_sweeps = 250
n_traj = 6


def random_spins(N):
    return np.random.choice([-1,1], size=(N,N))


def energia(grid):
    E = 0
    for i in range(N):
        for j in range(N):
            E += -J * grid[i,j]*(grid[(i+1)%N,j] + grid[i,(j+1)%N])
    return E / (N*N)


def sweep(grid, beta, E):

    for _ in range(N*N):

        i = np.random.randint(N)
        j = np.random.randint(N)

        neighbors = (
            grid[(i+1)%N,j] + grid[(i-1)%N,j] +
            grid[i,(j+1)%N] + grid[i,(j-1)%N]
        )

        dE = 2 * J * grid[i,j] * neighbors / (N*N)

        if dE <= 0 or np.random.rand() < np.exp(-beta * dE * (N*N)):
            grid[i,j] *= -1
            E += dE

    return E


def simulate(grid):

    E = energia(grid)
    M = np.sum(grid)/(N*N)

    E_list = [E]
    M_list = [M]

    for _ in range(n_sweeps):

        E = sweep(grid, beta, E)
        M = np.sum(grid)/(N*N)

        E_list.append(E)
        M_list.append(M)

    return np.array(E_list), np.array(M_list), grid


initial_grid = random_spins(N)

E_trajs = []
M_trajs = []

for k in range(n_traj):

    np.random.seed(k)
    grid = random_spins(N)

    E, M, grid_final = simulate(grid)

    E_trajs.append(E)
    M_trajs.append(M)

    if k == 0:
        final_grid = grid_final.copy()


fig = plt.figure(figsize=(12,4))
gs = gridspec.GridSpec(1,3, width_ratios=[1,2,1])

ax0 = fig.add_subplot(gs[0])
ax0.imshow(initial_grid, cmap='RdBu', vmin=-1, vmax=1)
ax0.set_title("Antes")
ax0.set_xticks([]); ax0.set_yticks([])

ax1 = fig.add_subplot(gs[1])

epochs = np.arange(len(E_trajs[0])) * (N*N)

for E, M in zip(E_trajs, M_trajs):
    ax1.plot(epochs, E, color='black', alpha=0.5)
    ax1.plot(epochs, M, color='red', alpha=0.5)

ax1.set_xlabel("Épocas")





ax1.plot([], [], color='black', label='Energía')
ax1.plot([], [], color='red', label='Magnetización')

ax1.set_xlabel("Épocas")
ax1.set_title("Durante")
ax1.legend()



ax2 = fig.add_subplot(gs[2])
ax2.imshow(final_grid, cmap='RdBu', vmin=-1, vmax=1)
ax2.set_title("Despues")
ax2.set_xticks([]); ax2.set_yticks([])

plt.tight_layout()
plt.savefig("2.a.pdf")
plt.close()

N = 60
J = 1.0

beta_coarse = np.linspace(0.2, 0.7, 12)
beta_fine = np.linspace(0.40, 0.47, 40)
beta_values = np.unique(np.concatenate((beta_coarse, beta_fine)))

beta_c = 0.5 * np.log(1 + np.sqrt(2))


@njit
def random_spins(N):
    spins = np.empty((N, N), dtype=np.int8)
    for i in range(N):
        for j in range(N):
            if np.random.random() < 0.5:
                spins[i, j] = 1
            else:
                spins[i, j] = -1
    return spins


@njit
def energia_total(spins):
    E = 0.0
    N = spins.shape[0]
    for i in range(N):
        for j in range(N):
            E += -spins[i, j] * (spins[(i+1)%N, j] + spins[i, (j+1)%N])
    return E


@njit
def sweep(spins, beta, E):
    N = spins.shape[0]

    for _ in range(N * N):

        i = np.random.randint(0, N)
        j = np.random.randint(0, N)

        s = spins[i, j]

        neighbors = (
            spins[(i+1)%N, j] + spins[(i-1)%N, j] +
            spins[i, (j+1)%N] + spins[i, (j-1)%N]
        )

        dE = 2.0 * s * neighbors

        if dE <= 0 or np.random.random() < np.exp(-beta * dE):
            spins[i, j] = -s
            E += dE

    return E


@njit
def sample_energies(spins, beta, thermal, samples, stride):

    N = spins.shape[0]
    E = energia_total(spins)

    for _ in range(thermal):
        E = sweep(spins, beta, E)

    energies = np.empty(samples)

    for k in range(samples):

        for _ in range(stride):
            E = sweep(spins, beta, E)

        energies[k] = E / (N * N)

    return energies


spins = random_spins(N)

Cv = np.zeros(len(beta_values))

for idx, beta in enumerate(beta_values):

    if abs(beta - beta_c) < 0.03:
        thermal = 300
        samples = 1500
        stride = 5
    else:
        thermal = 100
        samples = 400
        stride = 3

    energies = sample_energies(spins, beta, thermal, samples, stride)

    mu = np.mean(energies)
    mu2 = np.mean(energies * energies)

    Cv[idx] = beta**2 * N**2 * (mu2 - mu * mu)


beta_peak = beta_values[np.argmax(Cv)]


plt.figure(figsize=(8,6))

plt.plot(beta_values, Cv, '-', color='black', lw=1)

plt.axvline(beta_c, color='red', linestyle='--', label='β crítico teórico')
plt.axvline(beta_peak, color='blue', linestyle=':', label='β pico numérico')

plt.xlabel('β')
plt.ylabel('Capacidad calorífica')
plt.title('Modelo de Ising 2D')

plt.legend()

plt.savefig("2.b.pdf")
plt.close()

A = 1000
B = 20
lambda_U = np.log(2) / (23.4/1440)
lambda_Np = np.log(2) / 2.36

def sistema(t, y):
    U, Np, Pu = y
    dU = A - lambda_U * U
    dNp = lambda_U * U - lambda_Np * Np
    dPu = lambda_Np * Np - B * Pu
    return [dU, dNp, dPu]

U_eq = A / lambda_U
Np_eq = lambda_U * U_eq / lambda_Np
Pu_eq = lambda_Np * Np_eq / B

print(f"Estado estable teórico: U={U_eq:.1f}, Np={Np_eq:.1f}, Pu={Pu_eq:.1f}")

t_span = (0, 30)
t_eval = np.linspace(0, 30, 1000)
y0 = [10, 10, 10]

sol = solve_ivp(sistema, t_span, y0, t_eval=t_eval)



fig, axes = plt.subplots(3, 1, figsize=(10, 8), sharex=True)
titles = ['Uranio-239', 'Neptunio-239', 'Plutonio-239']
eq_values = [U_eq, Np_eq, Pu_eq]

for i, (ax, title, eq) in enumerate(zip(axes, titles, eq_values)):
    ax.plot(sol.t, sol.y[i], 'b-', linewidth=2)
    ax.axhline(y=eq, color='r', linestyle='--', label=f'Estado estable: {eq:.1f}')
    ax.set_ylabel('Cantidad')
    ax.set_title(title)
    ax.legend()

axes[-1].set_xlabel('Tiempo (días)')
plt.tight_layout()
plt.savefig('3.a.pdf')
plt.show()


def detectar_estabilidad(sol, tol=1e-3):
    derivadas = np.abs(np.gradient(sol.y, axis=1))
    magnitud = np.max(derivadas, axis=0)

    for i in range(len(magnitud)):
        if magnitud[i] < tol:
            return sol.t[i]
    return None

t_estable = detectar_estabilidad(sol)

def sde_simulation(t_max=30, dt=0.01):
    n_steps = int(t_max / dt)
    t = np.linspace(0, t_max, n_steps)

    trajectories = []
    for _ in range(5):
        U, Np, Pu = 10, 10, 10
        U_traj, Np_traj, Pu_traj = [U], [Np], [Pu]

        for _ in range(n_steps-1):
            W = np.random.normal(0, 1)
            S = np.random.choice([-1, 1])

            mu_U = A - lambda_U * U
            sigma_U = np.sqrt(A + lambda_U * U)

            K1_U = dt * mu_U + (W - S) * np.sqrt(dt) * sigma_U
            K2_U = dt * (A - lambda_U * (U + K1_U)) + (W + S) * np.sqrt(dt) * np.sqrt(A + lambda_U * (U + K1_U))
            U_new = U + 0.5 * (K1_U + K2_U)

            dNp = (lambda_U * U - lambda_Np * Np) * dt
            dPu = (lambda_Np * Np - B * Pu) * dt

            U, Np, Pu = max(0, U_new), Np + dNp, Pu + dPu

            U_traj.append(U)
            Np_traj.append(Np)
            Pu_traj.append(Pu)

        trajectories.append((U_traj, Np_traj, Pu_traj))

    return t, trajectories

t, trajectories = sde_simulation()

fig, axes = plt.subplots(3, 1, figsize=(10, 8), sharex=True)
titles = ['Uranio-239', 'Neptunio-239', 'Plutonio-239']

sol = solve_ivp(sistema, (0, 30), [10, 10, 10], t_eval=t)

for i, (ax, title) in enumerate(zip(axes, titles)):
    ax.plot(sol.t, sol.y[i], 'k-', linewidth=2, label='Determinista')

    for traj in trajectories:
        ax.plot(t, traj[i], 'b-', alpha=0.5, linewidth=0.8)

    ax.set_ylabel('Cantidad')
    ax.set_title(title)
    ax.legend()
    ax.grid(True, alpha=0.3)

axes[-1].set_xlabel('Tiempo (días)')
plt.tight_layout()
plt.savefig('3.b.pdf')
plt.close()

@njit
def sde_trayectoria(t_max, dt, A, B, lambda_U, lambda_Np):
    n_steps = int(t_max / dt)

    U, Np, Pu = 10.0, 10.0, 10.0

    U_traj = np.zeros(n_steps)
    Np_traj = np.zeros(n_steps)
    Pu_traj = np.zeros(n_steps)

    for i in range(n_steps):
        W = np.random.normal(0, 1)
        S = 1 if np.random.rand() < 0.5 else -1

        mu_U = A - lambda_U * U
        mu_Np = lambda_U * U - lambda_Np * Np
        mu_Pu = lambda_Np * Np - B * Pu

        sigma_U = np.sqrt(max(0, A + lambda_U * U))
        sigma_Np = np.sqrt(max(0, lambda_U * U + lambda_Np * Np))
        sigma_Pu = np.sqrt(max(0, lambda_Np * Np + B * Pu))

        U += dt * mu_U + np.sqrt(dt) * sigma_U * W
        Np += dt * mu_Np + np.sqrt(dt) * sigma_Np * W
        Pu += dt * mu_Pu + np.sqrt(dt) * sigma_Pu * W

        if U < 0: U = 0
        if Np < 0: Np = 0
        if Pu < 0: Pu = 0

        U_traj[i] = U
        Np_traj[i] = Np
        Pu_traj[i] = Pu

    return U_traj, Np_traj, Pu_traj

def gillespie_simulation(t_max=30):
    R = np.array([[1, 0, 0],
                  [-1, 1, 0],
                  [0, -1, 1],
                  [0, 0, -1]])

    trajectories = []

    for _ in range(5):
        Y = np.array([10, 10, 10])
        t = 0
        times = [0]
        states = [Y.copy()]

        while t < t_max:
            tasas = np.array([A,
                             lambda_U * Y[0],
                             lambda_Np * Y[1],
                             B * Y[2]])

            tasa_total = np.sum(tasas)
            if tasa_total == 0:
                break

            tau = np.random.exponential(1 / tasa_total)

            probs = tasas / tasa_total
            evento = np.random.choice(4, p=probs)

            Y = Y + R[evento]
            t += tau

            if len(times) == 1 or t - times[-1] > 0.1:
                times.append(t)
                states.append(Y.copy())

        trajectories.append((times, np.array(states)))

    return trajectories

trajectories = gillespie_simulation()

fig, axes = plt.subplots(3, 1, figsize=(10, 8), sharex=True)
titles = ['Uranio-239', 'Neptunio-239', 'Plutonio-239']

sol = solve_ivp(sistema, (0, 30), [10, 10, 10], t_eval=np.linspace(0, 30, 1000))

for i, (ax, title) in enumerate(zip(axes, titles)):
    ax.plot(sol.t, sol.y[i], 'k-', linewidth=2, label='Determinista')

    for times, states in trajectories:
        ax.step(times, states[:, i], 'b-', alpha=0.5, where='post')

    ax.set_ylabel('Cantidad')
    ax.set_title(title)
    ax.legend()

axes[-1].set_xlabel('Tiempo (días)')
plt.tight_layout()
plt.savefig('3.c.pdf')
plt.show()

@njit
def gillespie_critical(n_trajectories, t_max, critical_level, A, B, lambda_U, lambda_Np):

    k = 0

    for _ in range(n_trajectories):

        Y0, Y1, Y2 = 10.0, 10.0, 10.0
        t = 0.0

        while t < t_max:

            tasa0 = A
            tasa1 = lambda_U * Y0
            tasa2 = lambda_Np * Y1
            tasa3 = B * Y2

            total = tasa0 + tasa1 + tasa2 + tasa3

            if total == 0:
                break

            tau = np.random.exponential(1.0 / total)
            t += tau

            r = np.random.rand() * total

            if r < tasa0:
                Y0 += 1
            elif r < tasa0 + tasa1:
                Y0 -= 1; Y1 += 1
            elif r < tasa0 + tasa1 + tasa2:
                Y1 -= 1; Y2 += 1
            else:
                Y2 -= 1

            if Y0 < 0: Y0 = 0
            if Y1 < 0: Y1 = 0
            if Y2 < 0: Y2 = 0

            if Y2 >= critical_level:
                k += 1
                break

    return k


@njit
def sde_critical(n_trajectories, t_max, critical_level, A, B, lambda_U, lambda_Np):

    k = 0
    dt = 0.01

    for _ in range(n_trajectories):

        U, Np, Pu = 10.0, 10.0, 10.0
        t = 0.0

        while t < t_max:

            if Pu >= critical_level:
                k += 1
                break

            W = np.random.normal(0, 1)
            S = 1.0 if np.random.rand() < 0.5 else -1.0

            mu_U = A - lambda_U * U
            sigma_U = np.sqrt(max(0.0, A + lambda_U * U))

            K1_U = dt * mu_U + (W - S) * np.sqrt(dt) * sigma_U
            K2_U = dt * (A - lambda_U * (U + K1_U)) \
                   + (W + S) * np.sqrt(dt) * np.sqrt(max(0.0, A + lambda_U * (U + K1_U)))

            U_new = U + 0.5 * (K1_U + K2_U)

            dNp = (lambda_U * U - lambda_Np * Np) * dt
            dPu = (lambda_Np * Np - B * Pu) * dt

            U = max(0.0, U_new)
            Np += dNp
            Pu += dPu

            t += dt

    return k



from scipy.stats import beta

def estimate_critical_probability(n_trajectories=1000, t_max=30, critical_level=80):

    k_gillespie = gillespie_critical(
        n_trajectories, t_max, critical_level, A, B, lambda_U, lambda_Np
    )

    k_sde = sde_critical(
        n_trajectories, t_max, critical_level, A, B, lambda_U, lambda_Np
    )

    def beta_interval(k, n):
        alpha = 1 + k
        beta_ = 1 + n - k
        p_mean = alpha / (alpha + beta_)
        p_std = np.sqrt((alpha * beta_) / ((alpha + beta_)**2 * (alpha + beta_ + 1)))
        return p_mean * 100, p_std * 100

    p_gillespie, err_gillespie = beta_interval(k_gillespie, n_trajectories)
    p_sde, err_sde = beta_interval(k_sde, n_trajectories)

    with open('3.d.txt', 'w') as f:
        f.write("PROBABILIDAD DE CONCENTRACIÓN CRÍTICA (80 unidades de Pu en 30 días)\n")
        f.write("="*60 + "\n\n")

        f.write(f"Número de trayectorias: {n_trajectories}\n\n")

        f.write("Método Gillespie:\n")
        f.write(f"  Trayectorias que alcanzan criticalidad: {k_gillespie}\n")
        f.write(f"  Probabilidad: {p_gillespie:.2f}% ± {err_gillespie:.2f}%\n\n")

        f.write("Método SDE :\n")
        f.write(f"  Trayectorias que alcanzan criticalidad: {k_sde}\n")
        f.write(f"  Probabilidad: {p_sde:.2f}% ± {err_sde:.2f}%\n\n")

        f.write("Discusión:\n")
        f.write("La probabilidad de alcanzar la concentración crítica es baja en Gillespie y Metropolis.\n")
        f.write("El método de Gillespie tiende a dar valores más conservadores al modelar eventos discretos,\n")
        f.write("mientras que la aproximación SDE puede sobreestimar las fluctuaciones.\n")

    print(f"Gillespie: {p_gillespie:.2f}% ± {err_gillespie:.2f}%")
    print(f"SDE: {p_sde:.2f}% ± {err_sde:.2f}%")